fixup! net, diet: Make igmp and mcast ioctls depend on IP_MULTICAST
Fix undefined reference to `sysctl_igmp_max_memberships'.

Signed-off-by: Tom Zanussi <tom.zanussi@linux.intel.com>