fixup! net, diet: Make rtnetlink optional
Fix undefined reference to `netdev_rss_key', and also help out
netdev_rss_key_fill() callers, which we haven't seen problems with
because we haven't configured in any drivers with callers yet.

Signed-off-by: Tom Zanussi <tom.zanussi@linux.intel.com>